### ISSUE TITLE
Add Bottom navigation menu

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia-repo#3]
- [x] Add the bottom navigation menu. The Bottom navigation menu consists of: Home page, scan QR, advanced search, and Add child icons.
![image](https://user-images.githubusercontent.com/58034047/84900345-9fce8300-b0b2-11ea-9b40-b375f6d1ff17.png)
- [x] Use Add child icon[ here](https://github.com/OpenSRP/opensrp-client-child/blob/master/opensrp-child/src/main/res/drawable-xxxhdpi/ic_tabmenu_addchild.png).
- [x] Home - navigates to the child register and is blue when on the register, otherwise it is gray.
- [x] Scan QR - navigates to the device camera to read QR code. 
- [x] Add Child - navigates to the child registration form. 
- [x] Advanced search - this opens the advance search tab.

**Comment by cafootitt** [comment]
@AnnieMungai What about advanced search?

**Comment by AnnieMungai** [comment]
Debug v: 0.0.1 (19th June)

Looks good.
