### ISSUE TITLE
Implement the Side Menu

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-unicef-tunisia-repo#6]
- [ ] Implement the side menu with details as shown below. 
![TM5](https://user-images.githubusercontent.com/58034047/85106267-96f5c280-b214-11ea-9e11-b09f3ff4b3de.png)
- Tapping on the change language icon or the drop-down menu next to the icon displays 3 languages: Arabic, French, English. User can select the language they want to use within the app. Selecting any of the languages changes the app language to the selected one.  The change language icon displays the current language the app is in. 
- Tapping on the *add new child* opens a child's registration form. 
- Tapping on the record out of catchment vaccination opens the *record immunization for child out of catchment area form*
- Tapping on register redirects user to the register home page.
- Tapping on reports will open the in-app reporting tab. 
- The sync button will display the time since the last sync.

**Comment by cafootitt** [comment]
@AnnieMungai please see message in Slack on updates to make to this issue.

**Comment by AnnieMungai** [comment]
@cafootitt side menu updates done. This is now ready for engineering.

**Comment by AnnieMungai** [comment]
Debug v: 0.0.1 (19th June)

Looks good.
